#!/bin/bash
set -euo pipefail

# lock-agent.sh - Hash-lock agent files to prevent drift
# Usage: scripts/lock-agent.sh <agent_name> [agent_name2] ...

AGENTS_PATH="packages/agents"
PULSER_RC=".pulserrc"

if [ $# -eq 0 ]; then
    echo "Usage: $0 <agent_name> [agent_name2] ..."
    echo "Available agents: repo keykey basher caca claude"
    exit 1
fi

# Initialize .pulserrc if it doesn't exist
if [ ! -f "$PULSER_RC" ]; then
    echo "# Agent hash locks - DO NOT EDIT MANUALLY" > "$PULSER_RC"
    echo "# Generated by scripts/lock-agent.sh" >> "$PULSER_RC"
    echo "" >> "$PULSER_RC"
fi

for agent in "$@"; do
    agent_path="$AGENTS_PATH/$agent"
    
    if [ ! -d "$agent_path" ]; then
        echo "❌ Agent directory not found: $agent_path"
        continue
    fi
    
    echo "🔒 Locking agent: $agent"
    
    # Calculate hash of all files in agent directory
    if command -v shasum >/dev/null 2>&1; then
        hash=$(find "$agent_path" -type f -exec shasum -a 256 {} \; | sort | shasum -a 256 | cut -d' ' -f1)
    else
        hash=$(find "$agent_path" -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
    fi
    
    # Update or add hash in .pulserrc
    if grep -q "^$agent=" "$PULSER_RC"; then
        # Update existing hash
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/^$agent=.*/$agent=$hash/" "$PULSER_RC"
        else
            sed -i "s/^$agent=.*/$agent=$hash/" "$PULSER_RC"
        fi
    else
        # Add new hash
        echo "$agent=$hash" >> "$PULSER_RC"
    fi
    
    echo "✅ Agent $agent locked with hash: ${hash:0:12}..."
done

echo ""
echo "🔐 Agent locks updated in $PULSER_RC"
echo "💡 Commit this file to enforce hash verification in CI"
